name             'rogue'
maintainer       'Ami Rahav'
maintainer_email 'amiram.rahav@eglobaltech.com'
description      'Installs/Configures the ROGUE JCTD project'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.4'

depends 'nginx'
depends 'apt'
depends 'build-essential'
depends 'git'
depends 'python'
depends 'openssl'
depends 'ohai'
depends 'hostsfile'
depends 'database'
depends 'java'
depends 'tomcat'
depends 'supervisord'
depends 'runit'
depends 'git'
